### PR TITLE
Submodule update

### PR DESCRIPTION
**Pull request by joluxer**
The new project structure, that uses git-submodules, requires some more little actions during an update. This tries to introduce those additional actions.

### CODE REVIEW

**Comment by joluxer** [comment]
As this is eventually a sensitive topic I would like to mark this PR still as WIP, until we a confident, that the update process works.

There should be involved a lot of testing. So lets make plan for this. I'll start testing the Linux update procedure during the weekend.

Regards, 

J'Lo

**Comment by joluxer** [comment]
Beside the main topic of `git submodule update...` I'm trying to improve some small things on the existing scripts, just because I touched them.

If this is too much off-topic, tell me, so I can avoid such mixtures in the future.

**Comment by thiagoralves** [comment]
Thanks for working on this. Feel free to make your changes on the scripts on this PR. I’ll take a look at them on Monday and test everything.

About you comment on providing help with the embedded stuff, that would be most appreciated. I don’t know if you’re aware of the issues on ESP32. Some users are reporting crashes that I can’t debug. It seems to be related with just some specific ESP32 boards. There is a good discussion here if you want to follow the subject: https://openplc.discussion.community/post/esp32-gpio-pins-non-operable-13473290

**Comment by joluxer** [comment]
Hi @thiagoralves !

Where can we discuss implementation details for the OpenPLC Editor embedded part? I think this is off-topic for this thread here and even for the support thread in the discussion forum. Is there a github issue or is there a forum section? 

I'm asking, because my questions will be often highly technical and detailed, so I would not like to discuss this in the forum thread, where our users might get overwhelmed or confused by this type of discussion. In other words I would like to seperate support threads from implementation discussions for issue solution or even features and improvement.

I have at least two different perspectives of view onto the OpenPLC project. One is the user perspective, where our audience is a PLC user and/or PLC programmer, who has not necessarily knowledge about PLC core implementation on different platforms and execution environments. The other perspective is the developer perspective, where I personally have deep knowledge of MCUs, some knowledge of PLC core implementation, operating systems (in my case especially Linux), automated build systems (what the OpenPLC-Editor project definitely is), and more. Therefore the seperation of discussion types would make sense for me.

If you have the experience - or even the opinion - that our audience is keen - and somewhat robust - for technical details of the OpenPLC implementation, then I'm also open to discuss issue solution inside the support threads - but I'm unsure.

Best regards,
J'Lo

**Comment by thiagoralves** [comment]
Hi @joluxer I just sent you a PM on OpenPLC Forum. We can coordinate our technical discussions from there.

**Comment by joluxer** [comment]
I could not find problems, when simulating update on Linux.

**Comment by joluxer** [comment]
I do a rebase to the new master, to make the merge easier.

**Comment by thiagoralves** [comment]
This looks good to me. Just one thing, you might want to consider updating the [update.sh](https://github.com/thiagoralves/OpenPLC_Editor/blob/master/update.sh) script as well as you did with the update.cmd batch file.

**Comment by thiagoralves** [comment]
Let me know once this is good to merge and I'll merge it

**Pull request merged**
