### PR TITLE
Stm32 can bus block added & tested (WORKING)

### PR DESCRIPTION
**Pull request by Aurentiaco35**
Hello Thiago,

We added the CAN blocks for STM32 family into the editor. We also did couple tests with different boards, it's completely functional. The usage scenario is implemented with an example FBD project inside the examples folder of editor.

Please review the pull request and turn back to us. We appreciate your help on this.

Best regards
pcan
setup
toThiago

### CODE REVIEW

**Comment by dogualpay** [comment]
@thiagoralves Thanks for the help. After almost 2 years we did it ! 💯 💯 💯 💯 💯
@Aurentiaco35 Well done brother 🥇

**Comment by Aurentiaco35** [comment]
1. We need that file for enable stm32 hal libraries. I tried to add it in your .py but unfortunately it is not working thats why I added like that.
2. Done 
3. Done
4. Done
Could you check them again please

**Comment by thiagoralves** [comment]
1. Have you tried adding it to editor/arduino/examples/Baremetal/arduino_libs.h like this:
```
#ifdef USE_STM32CAN_BLOCK
    #define HAL_CAN_MODULE_ENABLED
    #include "modules/stm32can.c"
#endif
```
I don't see why it would be any different than including a separate file.

**Comment by Aurentiaco35** [comment]
Yes I tried it and I got an error.

**Comment by thiagoralves** [comment]
Got it. Seems that there is a specific requirement to have the file named as it is then.  I’ll go ahead and merge. Thanks!

**Pull request merged**
