### PR TITLE
Python 3.12 editor missing casts

### PR DESCRIPTION
**Pull request by joluxer**
Resolve more GUI crashes resulting from missing int() cast.

### CODE REVIEW

**Comment by thiagoralves** [comment]
What version of wxPython are you using with this Python 3.12 branch?

**Comment by joluxer** [comment]
Hi,
I'm using `dev-python/wxpython-4.2.1-r2`, which is in the system package repository of Gentoo's portage.

**Comment by joluxer** [comment]
I'm currently testing my changes primarily on Desktop Linux (uptodate Gentoo) and also on Windows 11. 

Next tests will go on Alpine Linux for the runtime component in Docker, in virtual machines an on small SBC for long-term running.
Some RISC-V Linux devices from Milk-V will be tested as well as microcontrollers, there with timing evaluation.

Up to here it is a great deal of code generator for my professional work and also my hobby projects. I love to work with it.

**Comment by joluxer** [comment]
So, how would you like proceed? 

I cannot test on macOS, but I also cannot work with an editor, that crashes on every second action I do. Even on Windows, using your self-contained installation set, I'm faced with those problems. So, I think, those crashes do not come from the minor version bump, as far as I remember, in Windows is wxpython 4.2.0 active.

I've tried to keep the modifications small to a minimal common set. I think going to explicit casts should not do any harm. More isn't in this patch set. And - to be honest - I'm not a seasoned python programmer, I'm a seasoned embedded guy. But those data type problems where to easy for me not be fixed.

I can do my tests on a downgraded version of wxpython-4.2.0 with Python-3.11, if that is more to your intention. then we have a version, that is tested on both versions of wxpython an the python interpreter. 
But Python-3.11 and wxpython-4.2.0 will be available for a limited time only, then we need a version bump. These are on the edge to be phased out in some Linux distributions.

My motivation for support is still the excellent idea behind the project and its promising implementation.
It is one of the most promising open projects for my embedded world for the past 20 years in building management systems and industrial automation and I'm still excited.

**Comment by joluxer** [comment]
I've inspected the dependency tree on my Gentoo systems. Downgrading to wxpython-4.2.0 is an acceptable compromise to get the OpenPLC project forward. And, as it is a common thing on Gentoo systems to have multiple python versions available - currently python 3.11 and 3.12 are the supported version slots - this is good for me either.

By the way: Kicad (currently v7.0.10) is faced with the same versioning problems on wxpython and python interpreter versions, but with those guys I would like to keep up.

**Comment by thiagoralves** [comment]
I think if we can keep it running on the latest wxPython then that’s better. Windows and macOS versions are running on Python 3.9 (or 3.10 I don’t remember) with wxPython 4.2.0. I’m not facing crashes on that setup (neither on Mac or Windows), but if possible I would like to make it work with newer Python and wxPython ask well for the systems that accept them. 

So, keep your tests and fixes on 3.12 with wxPython 4.2.1 please. So far your modifications haven’t impacted Windows and macOS on wxPython 4.2.0, and that’s why I merged them. I still need to test your latest PR. As long as the code can run on both setups (4.2.1 and 4.2.0) I’m fine with it.

**Comment by thiagoralves** [comment]
“It is one of the most promising open projects for my embedded world for the past 20 years in building management systems and industrial automation and I'm still excited.”

By the way, this made my day :) Thanks!!

**Comment by thiagoralves** [comment]
Just merged this PR. Also, I took a look at your other branches and the changes you did on the upload dialog. Feel free to merge them as well whenever you feel that they are ready.

**Comment by etisserant** [comment]
@joluxer , you must know about the [Beremiz project](https://github.com/beremiz/beremiz). @thiagoralves did organize OpenPLC project in a way that it is really hard to see that it takes most of its source code from Beremiz Project. Did you actually see it ? He made it really difficult to merge contributions from user like you back to the original project. 

Please make PRs on Beremiz rather than on OpenPLC, if possible.

**Comment by etisserant** [comment]
@joluxer please address pull request to the original project: [Beremiz](https://github.com/beremiz/beremiz). @thiagoralves just deleted previous comment.... Guess why !

**Comment by etisserant** [comment]
@thiagoralves there are screenshots (from many different users) of every steps in your process trying to hide origins of OpenPLC project, including deleting my messages. Please stop that shit or it will go legal, and you will lose it.

**Comment by joluxer** [comment]
Ok, I see your point of interest for contribution. But, I have no capacity to dive into some other project too. 
Here is my suggestion: I try to compare the affected files of the Beremiz project, do some patches and PR on it. but I cannot test the changed code (due to my capacity contraints). This way I would kindly ask for testing by you @etisserant and your team.

**Comment by etisserant** [comment]
signal-2024-08-11-145047_002

**Comment by etisserant** [comment]
> Ok, I see your point of interest for contribution. But, I have no capacity to dive into some other project too. Here is my suggestion: I try to compare the affected files of the Beremiz project, do some patches and PR on it. but I cannot test the changed code (due to my capacity contraints). This way I would kindly ask for testing by you @etisserant and your team.

Sure. If making a new PR is too much, the just send a patch against latest Beremiz  commit. Be sure I'll test your changes and keep commit message and authorship as-is. 

Please also have a look at beremiz C-runtime. It is only supporting Linux for now, but I am currently working on it and it will soon support every possible board.

Thanks in advance for your contribution.

**Comment by thiagoralves** [comment]
To anyone coming to this thread and seeing a lot of deleted comments, I want to explain my reasoning so it doesn’t come across the wrong way.

As stated at Autonomy's website, OpenPLC Editor GitHub repo, and several other places, OpenPLC incorporates a lot of source code from [Beremiz](https://github.com/beremiz/beremiz) created by [Edouard Tisserant](https://github.com/etisserant). There is absolutely no attempt to hide that. However, developing a successful product involves much more than just source code, which Edouard doesn’t seem to understand. Over the past few years, he has made some aggressive comments towards me because OpenPLC has gained more traction than Beremiz. To maintain a positive and constructive environment, I’ve decided to remove any posts he makes in OpenPLC's forums and repositories, particularly when they include inappropriate language.
 
That said, everyone here is welcome to collaborate with [Edouard](https://github.com/etisserant) and contribute to [Beremiz](https://github.com/beremiz/beremiz) if they choose. My main priority is to ensure our space remains focused and respectful.

**Comment by adclz** [comment]
@thiagoralves If you are so sure of yourself, why did you delete all those messages ?
Just let him be ashamed by his inappropriate language, then.
Still, could you stop using GIT this way making every contribution to Beremiz impossible ?

**Comment by etisserant** [comment]
> As stated at Autonomy's website, OpenPLC Editor GitHub repo, and several other places, OpenPLC incorporates a lot of source code from Beremiz created by Edouard Tisserant. There is absolutely no attempt to hide that.

This is a lie. As everybody can see in this commit : 9e995fec6597a1f00eb7382419e2b4ed21ae8c5c , project only shows origins since February 2024, but you started the OpenPLC project in 2012, and I had to force you to do so in a PR.

And again, GitHub users cannot access history of Beremiz and Matiec source code from your project. Even "Beremiz" project is renamed "Editor".

> That said, everyone here is welcome to collaborate with Edouard Tisserant and contribute to Beremiz if they choose.

As @joluxer was saying, he cannot afford working on 2 projects. So users doesn't really have a choice, because of the way you copy and patch source to your repository make it too much time consuming to propagate contributions to Beremiz. Can't you just properly fork Beremiz and MatIEC and make an OpenPLC branch ?

BTW, anyone looking closely to your message can see you edited it and replaced address behind my first name by the address of "adclz". This is really sneaky.  What are you trying ? Do you want to confuse readers ? Do you think this is the same person ?

FYI: I reported this discussion to GitHub staff for disinformation. Be sure to delete only really inappropriate messages...

**Comment by thiagoralves** [comment]
Edouard, 
That’s not a lie, how can you say that? Anyone can visit the Autonomy website or this repository to see all the references to your project on the homepage. You never forced me to acknowledge your work; I included those references because you requested them and when you requested them, not because I was compelled. From the beginning, our project has always credited you. You wanted more references, you wanted it more evident, that’s ok. I did it as you asked.

The issue here is not about acknowledgment but about communication. Your messages have often been aggressive and filled with hostility, making it difficult to understand your requests clearly. We’ve been there before, and here we are again. If your current request is to fork Beremiz and MatIEC on Git and create an OpenPLC branch, I can do that. It will disrupt the history of our project, but I’m willing to store that offline to accommodate your request. I’m traveling this week with limited access to my computer, so I will have to do it next week if you can wait.

With that being said, I must tell you that it is not the number of references I make to you on my project that will make Beremiz popular. As I have said before and will repeat, building a product takes more than just source code.

**Comment by thiagoralves** [comment]
You seem to know a lot about Autonomy and OpenPLC for someone who doesn't care...

Anyway, your requested changes were made (again). OpenPLC Editor default branch now has two submodules: one forked from [beremiz](https://github.com/beremiz/beremiz) and another forked from [matiec](https://github.com/beremiz/matiec). OpenPLC specific changes are on their own openplc-master branch for each submodule repository.

**Comment by etisserant** [comment]
It is not that I particularly care about your product, but I try to keep a non-exhaustive list of products that use Beremiz to feed the [Use Cases](https://beremiz.org/usecases) page on [beremiz.org](https://beremiz.org).  Please send me picture and text if you want to be listed there.

This is great that you at last did the two git submodules. Both communities will benefit from this. Thank you !

**Pull request merged**
