### PR TITLE
Can support

### PR DESCRIPTION
**Pull request by Rocketct**
ciao @thiagoralves here the first release,

i'm going to fix the comment on the big XML, add the support for 64Byte payload and increase the configurable parameter on ARDUINOCAN_CONF function block

### CODE REVIEW

**Comment by Rocketct** [comment]
@facchinm

**Comment by thiagoralves** [comment]
Ciao @Rocketct thanks for the contribution! Your PR has conflicts with the master branch. Could you please pull changes from the master branch and resolve the conflicts locally and push to the PR?

**Comment by Rocketct** [comment]
@thiagoralves done :)

**Comment by thiagoralves** [comment]
As an added bonus, it would be **GREAT** if you could include a CAN example project inside the /editor/examples folder :)

**Comment by brice-tkc** [comment]
Hi Aurentiaco35, i'm working on a project around ArduinoUNO R3 build with OpenPLC. i need to start a communication with the ARDUINOCAN fonction. could you get us some documentation, hardware configuration and example please. 
Thanks for your time and work
have a pleasant day.
bye

**Comment by brice-tkc** [comment]
Hi Aurentiaco35, i'm working on a project around ArduinoUNO R3 build with OpenPLC. i need to start a communication with the ARDUINOCAN fonction. could you get us some documentation, hardware configuration and example please.
Thanks for your time and work
have a pleasant day.
bye

image

**Pull request merged**
